services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./back/.env
    volumes:
      - ./back:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
