name: Deploy Cloud Run (fastapi)
on:
  push:
    branches: [main]
    paths:
      - "back/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: hgcj-472606
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi \
            --source . \
            --region asia-northeast3 \
            --allow-unauthenticated \
            --set-env-vars SECRET_KEY=${{ secrets.SECRET_KEY }},ACCESS_TOKEN_EXPIRE_MINUTES=60,DATABASE_URL=${{ secrets.DATABASE_URL }}
